### ISSUE TITLE
Faltando aspas no título da track

### ISSUE THREAD

**Issue by RamiroAlves** [marcosmss/react-fbq#1]
O evento do tipo track está dessa forma: 
const track = `fbq("track", ${title}, ${JSON.stringify(data)});`

Porém está fantando colocar o title entre aspas:
const track = `fbq("track", "${title}", ${JSON.stringify(data)});`

Caso contrário fica apresentando erro "title is not defined"

**Comment by marcosmss** [comment]
Boa tarde Ramiro, ajuste feito!

Agora:
 `const track = fbq("track", "${title}", ${JSON.stringify(data)});`
 
 
 Obrigado pelo comentário!
