### ISSUE TITLE
Add support for typescript?

### ISSUE THREAD

**Issue by oga-sven** [marcosmss/react-fbq#2]
Thanks for making this package. i saw your comment on https://github.com/zsajjad/react-facebook-pixel and decided to take one since its more maintanced. im using typescript. would you mind updating the package and add types?

**Comment by marcosmss** [comment]
Hi @oga-sven , how are you?

Thanks for the issue!!

Now we have support to Typescript in the react-fbq@2.0.0. However, it is being necessary to import like this:

Typescript projects:

`import ReactFbq from "react-fbq/dist/index";`

Javascript projects:

`import ReactFbq from "react-fbq";`

In the next patch, I'll fix this. For now, thanks! :)

**Comment by oga-sven** [comment]
Cool! i have another suggestion, but ill make a new issue for that!
